package POJO;
// Generated 2014-3-4 11:46:20 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private int uuid;
     private String title;
     private String author;
     private String introduction;
     private String context;
     private String img;
     private int gategory;
     private int format;
     private Date releasetime;
     private String editor;
     private String origin;
     private String comment;

    public Article() {
    }

	
    public Article(int uuid, String title, String author, String context, int gategory, int format, Date releasetime, String editor) {
        this.uuid = uuid;
        this.title = title;
        this.author = author;
        this.context = context;
        this.gategory = gategory;
        this.format = format;
        this.releasetime = releasetime;
        this.editor = editor;
    }
    public Article(int uuid, String title, String author, String introduction, String context, String img, int gategory, int format, Date releasetime, String editor, String origin, String comment) {
       this.uuid = uuid;
       this.title = title;
       this.author = author;
       this.introduction = introduction;
       this.context = context;
       this.img = img;
       this.gategory = gategory;
       this.format = format;
       this.releasetime = releasetime;
       this.editor = editor;
       this.origin = origin;
       this.comment = comment;
    }
   
    public int getUuid() {
        return this.uuid;
    }
    
    public void setUuid(int uuid) {
        this.uuid = uuid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getIntroduction() {
        return this.introduction;
    }
    
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }
    public String getContext() {
        return this.context;
    }
    
    public void setContext(String context) {
        this.context = context;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public int getGategory() {
        return this.gategory;
    }
    
    public void setGategory(int gategory) {
        this.gategory = gategory;
    }
    public int getFormat() {
        return this.format;
    }
    
    public void setFormat(int format) {
        this.format = format;
    }
    public Date getReleasetime() {
        return this.releasetime;
    }
    
    public void setReleasetime(Date releasetime) {
        this.releasetime = releasetime;
    }
    public String getEditor() {
        return this.editor;
    }
    
    public void setEditor(String editor) {
        this.editor = editor;
    }
    public String getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(String origin) {
        this.origin = origin;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


